// ===== All 58 Risk Signal Definitions — Unified Rulebook V3 =====

import type { RiskSignalDefinition } from "@/types/risk";

export const SIGNAL_DEFINITIONS: RiskSignalDefinition[] = [
  // ═══════════════════════════════════════════════════════════
  // CATEGORY 1: BEHAVIORAL INTELLIGENCE (Rules 1-14) — ALL STUBS
  // ═══════════════════════════════════════════════════════════
  {
    id: "R01_DECLARANT_CHANGE_3",
    name: "Declarant Change (Moderate)",
    ruleNumber: 1,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Changing customs declarant more than 3 times in 5 shipments suggests attempts to avoid pattern detection by customs authorities.",
    whatToFix: "Review declarant history. If changes are legitimate (staff turnover, etc.), document the reasons.",
  },
  {
    id: "R02_DECLARANT_CHANGE_6",
    name: "Declarant Change (Severe)",
    ruleNumber: 2,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "6+ declarant changes in 5 shipments is extremely unusual and a strong indicator of evasion tactics.",
    whatToFix: "Flag for immediate compliance review. Document all declarant changes with justification.",
  },
  {
    id: "R03_CHA_SWITCHING",
    name: "CHA Switching Within 15 Days",
    ruleNumber: 3,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Same importer using different Customs House Agents within 15 days suggests shopping for a compliant agent.",
    whatToFix: "Verify CHA relationships. Ensure consistent agent usage or document business reasons for changes.",
  },
  {
    id: "R04_PORT_SWITCHING",
    name: "Port Switching Pattern",
    ruleNumber: 4,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "Switching ports across consecutive shipments can indicate attempts to spread risk across jurisdictions.",
    whatToFix: "Consolidate port usage or provide documented business justification for each port change.",
  },
  {
    id: "R05_HS_CHANGE_SAME_DESC",
    name: "HS Code Changed, Description Same",
    ruleNumber: 5,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "Changing HS code while keeping the same product description is a classic misclassification tactic to reduce duty rates.",
    whatToFix: "Standardize HS codes for identical products. Consult tariff schedule for correct classification.",
  },
  {
    id: "R06_INACTIVITY_SPIKE",
    name: "Inactivity Followed by Spike",
    ruleNumber: 6,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Sudden large shipments after a period of inactivity can indicate stockpiling or dormant entity reactivation for fraud.",
    whatToFix: "Verify business continuity. Request purchase orders and contracts supporting the volume increase.",
  },
  {
    id: "R07_BELOW_THRESHOLD_SPLITTING",
    name: "Below Duty Threshold Splitting",
    ruleNumber: 7,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "Multiple small shipments just below duty thresholds is a strong indicator of deliberate value splitting to evade duties.",
    whatToFix: "Aggregate shipment values over the period. If total exceeds thresholds, full duty may apply.",
  },
  {
    id: "R08_REPEATED_AMENDMENTS",
    name: "Repeated Filing Amendments",
    ruleNumber: 8,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Frequent corrections in customs filings suggest either sloppy documentation or testing customs tolerance.",
    whatToFix: "Implement quality checks before filing. Review amendment history for patterns.",
  },
  {
    id: "R09_HIGH_RISK_CLUSTER",
    name: "High-Risk Importer Cluster",
    ruleNumber: 9,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "Linked entities (shared addresses, directors, or bank accounts) operating together multiply risk exposure.",
    whatToFix: "Map entity relationships. Verify each entity's independent legitimacy.",
  },
  {
    id: "R10_HS_CODE_CYCLING",
    name: "HS Code Cycling Pattern",
    ruleNumber: 10,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "Rotating HS codes (A→B→C→A) for similar goods is a sophisticated evasion technique to avoid automated detection.",
    whatToFix: "Standardize classification. File a binding tariff ruling for disputed products.",
  },
  {
    id: "R11_TRIAL_SHIPMENT",
    name: "Trial Shipment Pattern",
    ruleNumber: 11,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Small test shipments followed by large volumes can indicate testing customs scrutiny before committing fraud at scale.",
    whatToFix: "Apply same scrutiny to small and large shipments. Document volume progression.",
  },
  {
    id: "R12_CONSIGNEE_NETWORK",
    name: "Consignee Network Risk",
    ruleNumber: 12,
    category: "BEHAVIORAL",
    severity: "critical",
    isActive: false,
    whyItMatters: "Multiple consignees sharing the same address or contact details suggests shell entities used for layered fraud.",
    whatToFix: "Verify each consignee independently. Cross-check addresses and contact information.",
  },
  {
    id: "R13_SUPPLIER_ROTATION",
    name: "Supplier Rotation Pattern",
    ruleNumber: 13,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Changing supplier with every shipment prevents building a verification history and may indicate fabricated suppliers.",
    whatToFix: "Verify supplier legitimacy. Request business registration and trade references.",
  },
  {
    id: "R14_REPEATED_AMENDMENT_PATTERN",
    name: "Repeated Amendment Pattern",
    ruleNumber: 14,
    category: "BEHAVIORAL",
    severity: "major",
    isActive: false,
    whyItMatters: "Consistently filing more than 2 amendments per shipment indicates systemic documentation issues.",
    whatToFix: "Review filing procedures. Implement pre-submission quality checks.",
  },

  // ═══════════════════════════════════════════════════════════
  // CATEGORY 2: DOCUMENT VALIDATION & FORENSICS (Rules 15-26)
  // ═══════════════════════════════════════════════════════════
  {
    id: "R15_ITEM_COUNT_MISMATCH",
    name: "Invoice vs Packing List Item Count Mismatch",
    ruleNumber: 15,
    category: "DOCUMENT_FORENSICS",
    severity: "medium",
    isActive: true,
    whyItMatters: "Different item counts between Invoice and Packing List indicate data entry errors or document tampering.",
    whatToFix: "Compare Invoice and Packing List line by line. Ensure both list the exact same items.",
  },
  {
    id: "R16_INVOICE_TOTAL_MISMATCH",
    name: "Invoice Total vs Line Items Sum",
    ruleNumber: 16,
    category: "DOCUMENT_FORENSICS",
    severity: "critical",
    isActive: true,
    whyItMatters: "When the invoice total doesn't match the sum of line items, it indicates manipulation or calculation errors — customs will always catch this.",
    whatToFix: "Recalculate all line item values and verify the invoice total matches exactly.",
  },
  {
    id: "R17_LC_TOLERANCE_EXCEEDED",
    name: "LC Tolerance Exceeded",
    ruleNumber: 17,
    category: "DOCUMENT_FORENSICS",
    severity: "critical",
    isActive: true,
    whyItMatters: "Exceeding LC tolerance limits means the bank will reject the documents — shipment will be stranded.",
    whatToFix: "Align Invoice values within LC tolerance. If exceeded, request LC amendment before shipping.",
  },
  {
    id: "R18_CURRENCY_MISMATCH",
    name: "Currency Mismatch Across Documents",
    ruleNumber: 18,
    category: "DOCUMENT_FORENSICS",
    severity: "major",
    isActive: true,
    whyItMatters: "Different currencies in Invoice vs LC vs Packing List creates discrepancy risk and potential customs issues.",
    whatToFix: "Ensure all documents use the same currency. If LC specifies a currency, all documents must match.",
  },
  {
    id: "R19_CONSIGNEE_NAME_MISMATCH",
    name: "Different Consignee Names",
    ruleNumber: 19,
    category: "DOCUMENT_FORENSICS",
    severity: "critical",
    isActive: true,
    whyItMatters: "Consignee name mismatch across documents is a serious discrepancy — may indicate fraud or document mixing.",
    whatToFix: "Verify the correct consignee and ensure all documents reference the same entity with exact name match.",
  },
  {
    id: "R20_INCOTERMS_INCONSISTENT",
    name: "Inconsistent Incoterms",
    ruleNumber: 20,
    category: "DOCUMENT_FORENSICS",
    severity: "medium",
    isActive: true,
    whyItMatters: "Inconsistent delivery terms across documents create ambiguity about who bears costs and risks.",
    whatToFix: "Standardize incoterms across Invoice, LC, and transport documents.",
  },
  {
    id: "R21_GROSS_NET_LOGIC",
    name: "Gross vs Net Weight Logic Error",
    ruleNumber: 21,
    category: "DOCUMENT_FORENSICS",
    severity: "major",
    isActive: true,
    whyItMatters: "Gross weight must always exceed net weight (packaging has weight). When net > gross, the data is fabricated or incorrectly entered.",
    whatToFix: "Verify actual weights. Gross weight = Net weight + Packaging weight. Correct the lower value.",
  },
  {
    id: "R22_DUPLICATE_DOC_NUMBERS",
    name: "Duplicate Document Numbers",
    ruleNumber: 22,
    category: "DOCUMENT_FORENSICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Reused invoice or document numbers across shipments indicate recycled or forged documents.",
    whatToFix: "Verify document authenticity. Each shipment must have unique document numbers.",
  },
  {
    id: "R23_FONT_FORMAT_INCONSISTENCY",
    name: "Font/Format Inconsistency",
    ruleNumber: 23,
    category: "DOCUMENT_FORENSICS",
    severity: "medium",
    isActive: false,
    whyItMatters: "Different fonts or formatting within sections of the same invoice suggest document tampering or cut-paste forgery.",
    whatToFix: "Request original documents from source. Compare formatting against known-good templates.",
  },
  {
    id: "R24_SIGNATURE_REUSE",
    name: "Signature Pattern Reuse",
    ruleNumber: 24,
    category: "DOCUMENT_FORENSICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Identical signatures across unrelated suppliers is a strong indicator of document fabrication from a single source.",
    whatToFix: "Cross-reference signatures with known specimens. Request fresh signed documents.",
  },
  {
    id: "R25_TEMPLATE_CLONING",
    name: "Template Cloning Detected",
    ruleNumber: 25,
    category: "DOCUMENT_FORENSICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Same invoice template used by different exporters suggests a single entity creating documents for multiple fake suppliers.",
    whatToFix: "Verify each exporter independently. Request business registration documents.",
  },
  {
    id: "R26_SEQUENTIAL_INVOICE_MANIPULATION",
    name: "Sequential Invoice Manipulation",
    ruleNumber: 26,
    category: "DOCUMENT_FORENSICS",
    severity: "medium",
    isActive: false,
    whyItMatters: "Suspicious gaps or patterns in invoice numbering (e.g., skipping numbers systematically) can indicate selective document production.",
    whatToFix: "Request a complete invoice register. Verify sequential numbering is consistent.",
  },

  // ═══════════════════════════════════════════════════════════
  // CATEGORY 3: VALUATION INTELLIGENCE (Rules 27-37)
  // ═══════════════════════════════════════════════════════════
  {
    id: "R27_VALUE_KG_DEVIATION",
    name: "Value/kg Deviation from Expected",
    ruleNumber: 27,
    category: "VALUATION",
    severity: "major",
    isActive: true,
    whyItMatters: "Value per kilogram deviating more than 40% from expected range is a strong indicator of undervaluation or overvaluation.",
    whatToFix: "Verify unit prices against market rates. Prepare supporting documentation (contracts, market references).",
  },
  {
    id: "R28_THRESHOLD_PROXIMITY",
    name: "Value Near Regulatory Threshold",
    ruleNumber: 28,
    category: "VALUATION",
    severity: "major",
    isActive: false,
    whyItMatters: "Declared values repeatedly landing just below regulatory thresholds suggest deliberate undervaluation to avoid higher duty brackets.",
    whatToFix: "Compare declared values against duty threshold tables. Flag for manual review if consistently near limits.",
  },
  {
    id: "R29_FREIGHT_RATIO_HIGH",
    name: "Abnormally High Freight Ratio",
    ruleNumber: 29,
    category: "VALUATION",
    severity: "medium",
    isActive: true,
    whyItMatters: "Freight exceeding 30% of goods value is unusual and may indicate inflated freight to reduce declared goods value for customs.",
    whatToFix: "Verify freight charges against market rates. Compare with similar shipments on the same route.",
  },
  {
    id: "R30_INSURANCE_MISSING",
    name: "Insurance Missing for High-Value",
    ruleNumber: 30,
    category: "VALUATION",
    severity: "minor",
    isActive: true,
    whyItMatters: "High-value goods shipped without insurance is either negligent or indicates the declared value doesn't reflect actual value.",
    whatToFix: "Obtain insurance for high-value shipments. If goods are truly low-value, verify the declared amount.",
  },
  {
    id: "R31_EXCESSIVE_DISCOUNT",
    name: "Declared Discounts > 50%",
    ruleNumber: 31,
    category: "VALUATION",
    severity: "major",
    isActive: false,
    whyItMatters: "Discounts exceeding 50% are unusual in legitimate trade and may be used to artificially reduce customs value.",
    whatToFix: "Provide discount justification (volume deals, clearance sales, etc.) with supporting contracts.",
  },
  {
    id: "R32_LUXURY_UNDERPRICED",
    name: "Luxury Goods Below Market",
    ruleNumber: 32,
    category: "VALUATION",
    severity: "critical",
    isActive: false,
    whyItMatters: "Luxury goods priced significantly below market rates is a strong indicator of undervaluation fraud.",
    whatToFix: "Compare with retail or wholesale market prices. Provide authentication certificates.",
  },
  {
    id: "R33_INVOICE_SPLITTING",
    name: "Multiple Invoices Splitting Shipment",
    ruleNumber: 33,
    category: "VALUATION",
    severity: "critical",
    isActive: false,
    whyItMatters: "Splitting a single shipment across multiple invoices can be used to keep each below scrutiny thresholds.",
    whatToFix: "Verify if goods belong to a single transaction. Consolidate invoices if from same supplier/buyer pair.",
  },
  {
    id: "R34_PRICE_SMOOTHING",
    name: "Price Smoothing Fraud",
    ruleNumber: 34,
    category: "VALUATION",
    severity: "major",
    isActive: false,
    whyItMatters: "Unnaturally constant pricing across varying products or time periods suggests artificial price setting.",
    whatToFix: "Verify pricing against market fluctuations. Legitimate prices should vary with market conditions.",
  },
  {
    id: "R35_UNDERPRICING_HIGH_FREIGHT",
    name: "Underpricing with High Freight",
    ruleNumber: 35,
    category: "VALUATION",
    severity: "major",
    isActive: true,
    whyItMatters: "Low goods value combined with freight exceeding 25% is a known valuation fraud pattern — shifting value from dutiable goods to non-dutiable freight.",
    whatToFix: "Verify both goods value and freight charges independently. Total transaction cost should make commercial sense.",
  },
  {
    id: "R36_ARTIFICIAL_DISCOUNTING",
    name: "Artificial Discounting Pattern",
    ruleNumber: 36,
    category: "VALUATION",
    severity: "major",
    isActive: false,
    whyItMatters: "Discounts exceeding 40% vs standard pricing without clear commercial justification suggest price manipulation.",
    whatToFix: "Request supplier's standard price list and compare. Verify discount agreements in writing.",
  },
  {
    id: "R37_CURRENCY_ARBITRAGE",
    name: "Currency Arbitrage Pattern",
    ruleNumber: 37,
    category: "VALUATION",
    severity: "medium",
    isActive: false,
    whyItMatters: "Frequent changes in billing currency can be used to exploit exchange rate differences for value manipulation.",
    whatToFix: "Standardize currency for recurring trade relationships. Document reasons for any currency changes.",
  },

  // ═══════════════════════════════════════════════════════════
  // CATEGORY 4: PHYSICAL & LOGISTICS INTELLIGENCE (Rules 38-48)
  // ═══════════════════════════════════════════════════════════
  {
    id: "R38_DENSITY_ANOMALY",
    name: "Density Check Anomaly",
    ruleNumber: 38,
    category: "PHYSICAL_LOGISTICS",
    severity: "critical",
    isActive: true,
    whyItMatters: "Unrealistic weight-to-volume ratio for the declared commodity type suggests goods are not what they're declared as.",
    whatToFix: "Verify actual commodity. Cross-check weight and dimensions against known density for the declared goods.",
  },
  {
    id: "R39_PACKAGING_MISMATCH",
    name: "Packaging Type Mismatch",
    ruleNumber: 39,
    category: "PHYSICAL_LOGISTICS",
    severity: "major",
    isActive: true,
    whyItMatters: "Fragile goods in bulk packaging or delicate items without proper protection suggests goods misdeclaration.",
    whatToFix: "Verify packaging is appropriate for the declared goods. Request packing photos or inspection report.",
  },
  {
    id: "R40_CONTAINER_UTILIZATION",
    name: "Container Utilization Anomaly",
    ruleNumber: 40,
    category: "PHYSICAL_LOGISTICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Container less than 30% full or overpacked beyond 110% suggests either hidden goods or data fabrication.",
    whatToFix: "Verify container loading plan. Request stuffing report or container photos.",
  },
  {
    id: "R41_PALLET_CARGO_CONFLICT",
    name: "Pallet vs Loose Cargo Conflict",
    ruleNumber: 41,
    category: "PHYSICAL_LOGISTICS",
    severity: "medium",
    isActive: false,
    whyItMatters: "Declaring palletized goods when actually shipped loose (or vice versa) affects weight calculations and handling.",
    whatToFix: "Verify actual loading method. Ensure packing list matches physical packaging.",
  },
  {
    id: "R42_UNUSUAL_ROUTE",
    name: "Unusual Transit Route",
    ruleNumber: 42,
    category: "PHYSICAL_LOGISTICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Non-optimal shipping routes can indicate attempts to avoid inspection at certain ports or transshipment fraud.",
    whatToFix: "Verify business justification for route choice. Compare with standard shipping lanes.",
  },
  {
    id: "R43_TRANSPORT_MODE_MISMATCH",
    name: "Transport Mode Declaration Mismatch",
    ruleNumber: 43,
    category: "PHYSICAL_LOGISTICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Mismatch between declared and actual transport mode affects duty calculations and risk assessment.",
    whatToFix: "Verify actual transport mode. Ensure all documents consistently state the correct mode.",
  },
  {
    id: "R44_MULTIPLE_BORDER_CROSSINGS",
    name: "Multiple Border Crossings",
    ruleNumber: 44,
    category: "PHYSICAL_LOGISTICS",
    severity: "critical",
    isActive: false,
    whyItMatters: "Same shipment crossing multiple borders unnecessarily is a strong indicator of transshipment fraud or origin concealment.",
    whatToFix: "Verify route necessity. Request proof of origin and complete transit documentation.",
  },
  {
    id: "R45_TRANSIT_TIME_ANOMALY",
    name: "Transit Time Anomaly",
    ruleNumber: 45,
    category: "PHYSICAL_LOGISTICS",
    severity: "medium",
    isActive: false,
    whyItMatters: "Unusually short or long transit times can indicate document fabrication or unauthorized stops.",
    whatToFix: "Compare transit time with standard for the route. Request GPS tracking or transit logs.",
  },
  {
    id: "R46_PORT_AVOIDANCE",
    name: "Repeated Rerouting / Port Avoidance",
    ruleNumber: 46,
    category: "PHYSICAL_LOGISTICS",
    severity: "critical",
    isActive: false,
    whyItMatters: "Systematically avoiding certain ports suggests those ports have flagged the entity or commodity.",
    whatToFix: "Review shipping history. Test clearance at the avoided port with clean documentation.",
  },
  {
    id: "R47_ORIGIN_ROUTE_MISMATCH",
    name: "Origin-Route Mismatch",
    ruleNumber: 47,
    category: "PHYSICAL_LOGISTICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Transit through high-risk countries inconsistent with declared origin suggests possible transshipment or origin fraud.",
    whatToFix: "Verify certificate of origin. Request proof of manufacturing or sourcing from declared origin.",
  },
  {
    id: "R48_BORDER_TIMING",
    name: "Border Timing Pattern",
    ruleNumber: 48,
    category: "PHYSICAL_LOGISTICS",
    severity: "major",
    isActive: false,
    whyItMatters: "Arrival during low-control hours (late night, holidays) may indicate attempts to exploit reduced scrutiny.",
    whatToFix: "Schedule arrivals during normal business hours. Flag for priority inspection if pattern persists.",
  },

  // ═══════════════════════════════════════════════════════════
  // CATEGORY 5: NETWORK & ADVANCED ANOMALY (Rules 49-55) — ALL STUBS
  // ═══════════════════════════════════════════════════════════
  {
    id: "R49_SHARED_BANK_DETAILS",
    name: "Shared Bank Details Among Suppliers",
    ruleNumber: 49,
    category: "NETWORK_ADVANCED",
    severity: "critical",
    isActive: false,
    whyItMatters: "Multiple supposedly independent suppliers sharing the same bank account is a strong indicator of a shell company network.",
    whatToFix: "Verify each supplier's banking independently. Request bank confirmation letters.",
  },
  {
    id: "R50_CHA_IMPORTER_PAIR",
    name: "Repeated CHA-Importer Pair Risk",
    ruleNumber: 50,
    category: "NETWORK_ADVANCED",
    severity: "major",
    isActive: false,
    whyItMatters: "A specific CHA consistently paired with problematic importers suggests possible collusion.",
    whatToFix: "Review CHA's client portfolio. Flag for regulatory review if multiple issues found.",
  },
  {
    id: "R51_LINKED_CLUSTERS",
    name: "Linked Shipment Clusters",
    ruleNumber: 51,
    category: "NETWORK_ADVANCED",
    severity: "major",
    isActive: false,
    whyItMatters: "Shipments sharing HS codes, values, and timing patterns suggest coordinated activity to distribute risk.",
    whatToFix: "Analyze shipments as a group. Verify each is an independent transaction.",
  },
  {
    id: "R52_PEER_DEVIATION",
    name: "Peer Comparison Deviation",
    ruleNumber: 52,
    category: "NETWORK_ADVANCED",
    severity: "major",
    isActive: false,
    whyItMatters: "Values deviating more than 40% from peer averages (same HS code, same origin) suggest pricing manipulation.",
    whatToFix: "Compare with industry benchmarks. Provide market justification for deviation.",
  },
  {
    id: "R53_TIME_SERIES_SPIKE",
    name: "Time-Series Value Spike/Drop",
    ruleNumber: 53,
    category: "NETWORK_ADVANCED",
    severity: "major",
    isActive: false,
    whyItMatters: "Sudden value changes (>2x increase or >40% drop) without market justification suggest manipulation.",
    whatToFix: "Document market conditions driving the change. Provide supporting contracts or price agreements.",
  },
  {
    id: "R54_INCONSISTENT_GROWTH",
    name: "Inconsistent Growth Pattern",
    ruleNumber: 54,
    category: "NETWORK_ADVANCED",
    severity: "medium",
    isActive: false,
    whyItMatters: "Erratic volume or value fluctuations without business justification suggest non-organic trade patterns.",
    whatToFix: "Provide business growth documentation. Explain volume fluctuations with order history.",
  },
  {
    id: "R55_DATA_TOO_CLEAN",
    name: "Data Fields Too Clean / OCR Issues",
    ruleNumber: 55,
    category: "NETWORK_ADVANCED",
    severity: "medium",
    isActive: true,
    whyItMatters: "Overly rounded values across multiple fields can indicate fabricated data rather than real measurements.",
    whatToFix: "Verify values come from actual measurements/invoices, not manual rounded entries.",
  },

  // ═══════════════════════════════════════════════════════════
  // CATEGORY 6: INTELLIGENT COMBO RULES (Rules 56-58)
  // ═══════════════════════════════════════════════════════════
  {
    id: "R56_HIGH_RISK_COMBO",
    name: "High-Risk Combo: HS Mismatch + Low Value + New Supplier",
    ruleNumber: 56,
    category: "COMBO",
    severity: "critical",
    isActive: true,
    whyItMatters: "When HS code doesn't match the description AND value is suspiciously low, it's a high-confidence indicator of deliberate misclassification and undervaluation combined.",
    whatToFix: "Priority investigation required. Verify HS classification, market pricing, and supplier legitimacy independently.",
  },
  {
    id: "R57_SMUGGLING_PATTERN",
    name: "Smuggling Pattern: Port + Small Shipments + HS Change",
    ruleNumber: 57,
    category: "COMBO",
    severity: "critical",
    isActive: false,
    whyItMatters: "Port switching combined with small shipments and HS code changes is a textbook smuggling pattern.",
    whatToFix: "Refer to enforcement. Aggregate all related shipments for comprehensive investigation.",
  },
  {
    id: "R58_UNDERVALUATION_COMBO",
    name: "Undervaluation Combo: Low Value + High Freight + Discount",
    ruleNumber: 58,
    category: "COMBO",
    severity: "critical",
    isActive: true,
    whyItMatters: "Low declared value combined with high freight ratio creates a classic undervaluation pattern where dutiable value is shifted to non-dutiable costs.",
    whatToFix: "Reconstruct total transaction value. Verify freight charges and any discounts against market rates. Total cost must reflect commercial reality.",
  },
];

/** Quick lookup map by signal ID */
export const SIGNAL_MAP: Record<string, RiskSignalDefinition> = Object.fromEntries(
  SIGNAL_DEFINITIONS.map((s) => [s.id, s])
);

/** Get all signals for a category */
export function getSignalsByCategory(category: string): RiskSignalDefinition[] {
  return SIGNAL_DEFINITIONS.filter((s) => s.category === category);
}

/** Get only active (per-shipment evaluable) signals */
export function getActiveSignals(): RiskSignalDefinition[] {
  return SIGNAL_DEFINITIONS.filter((s) => s.isActive);
}
